<script setup>
import { onMounted,reactive,ref } from 'vue'
import { Check,X } from 'lucide-vue-next'
import StateBlock from '@/components/StateBlock.vue'
import AppPagination from '@/components/app/AppPagination.vue'
import { getOperationRequests,reviewOperationRequest } from '@/api/operations'
import { getApiErrorMessage } from '@/utils/apiError'
import { confirmAction, requestActionDialog } from '@/composables/useActionDialog'
import { useRequestGate } from '@/composables/useRequestGate'
import { APPROVAL_STATUSES,resolveApprovalStatus } from '@/config/operationStatus'
import './operations.css'
const loading=ref(false),loaded=ref(false),error=ref(''),message=ref(''),rows=ref([]),status=ref(''),appliedStatus=ref(''),busyId=ref('');const pager=reactive({current:1,size:10,total:0});const requestGate=useRequestGate();const formatTime=value=>value?String(value).replace('T',' '):'-'
async function load(page=pager.current){const current=requestGate.begin();loading.value=true;error.value='';try{const response=await getOperationRequests({current:page,size:pager.size,status:appliedStatus.value===''?undefined:appliedStatus.value});if(!requestGate.isCurrent(current))return;if(response.data?.code!==200)throw new Error(response.data?.message||'审批加载失败');const data=response.data.data||{};pager.current=Number(data.current)||page;pager.size=Number(data.size)||pager.size;pager.total=Number(data.total)||0;rows.value=data.records||[];loaded.value=true}catch(cause){if(requestGate.isCurrent(current)){error.value=cause instanceof Error&&!cause.response?cause.message:getApiErrorMessage(cause,'审批加载失败');loaded.value=true}}finally{if(requestGate.isCurrent(current))loading.value=false}}
function search(){appliedStatus.value=status.value;load(1)}async function review(row,approved){let rejectReason;if(!approved){const result=await requestActionDialog({title:'确认驳回申请',message:`申请 ${row.id} 将被驳回。`,confirmLabel:'驳回申请',inputLabel:'驳回原因',inputPlaceholder:'说明驳回原因',inputRequired:true,tone:'danger'});if(!result.confirmed)return;rejectReason=result.value}else if(!await confirmAction({title:'确认通过申请',message:`申请 ${row.id} 通过后将执行对应的高风险操作。`,confirmLabel:'通过申请',tone:'danger'}))return;busyId.value=String(row.id);error.value='';message.value='';try{const response=await reviewOperationRequest(row.id,{approved,rejectReason});if(response.data?.code!==200)throw new Error(response.data?.message||'审批操作失败');message.value=approved?'审批已通过':'审批已驳回';await load()}catch(cause){error.value=cause instanceof Error&&!cause.response?cause.message:getApiErrorMessage(cause,'审批操作失败')}finally{busyId.value=''}}
onMounted(()=>load(1))
</script>
<template><section class="workspace-view operations-page"><header class="dashboard-header"><div><p class="page-kicker">运营工作区</p><h2>高风险审批</h2></div></header><p v-if="error" class="alert error">{{ error }}</p><p v-if="message" class="alert success">{{ message }}</p><form class="glass-toolbar operations-toolbar" @submit.prevent="search"><label><span>审批状态</span><select v-model="status"><option value="">全部状态</option><option v-for="(item,value) in APPROVAL_STATUSES" :key="value" :value="value">{{ item.label }}</option></select></label><button type="submit" :disabled="loading">查询</button></form><StateBlock v-if="loading&&!loaded" type="loading" title="正在加载审批"/><StateBlock v-else-if="loaded&&!error&&!rows.length" title="暂无审批申请"/><section v-if="loaded&&rows.length" class="glass-panel operations-table-wrap"><table class="operations-table"><thead><tr><th>ID</th><th>类型</th><th>目标用户</th><th>申请人</th><th>状态</th><th>原因</th><th>申请时间</th><th>操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td>{{ row.id }}</td><td>{{ row.requestType }}</td><td>{{ row.targetUsername }}</td><td>{{ row.requesterName }}</td><td><span :class="['status-pill',`status-pill--${resolveApprovalStatus(row.status).tone}`]">{{ resolveApprovalStatus(row.status).label }}</span></td><td class="wrap-cell">{{ row.reason||row.rejectReason||'-' }}</td><td>{{ formatTime(row.createTime) }}</td><td class="operations-actions"><button v-if="Number(row.status)===0" class="secondary-button compact-button" type="button" :disabled="!!busyId" @click="review(row,true)"><Check :size="15"/>通过</button><button v-if="Number(row.status)===0" class="danger-button compact-button" type="button" :disabled="!!busyId" @click="review(row,false)"><X :size="15"/>驳回</button></td></tr></tbody></table></section><AppPagination v-if="loaded" :current="pager.current" :size="pager.size" :total="pager.total" :busy="loading" @change="load"/></section></template>
