import http from './http'
const path = (value) => encodeURIComponent(String(value))

export const getUsers = (params) => http.get('/admin/users', { params })
export const getUser = (userId) => http.get(`/admin/users/${path(userId)}`)
export const updateUser = (userId, data) => http.put(`/admin/users/${path(userId)}`, data)
export const updateUserStatus = (userId, data) => http.put(`/admin/users/${path(userId)}/status`, data)
export const deleteUser = (userId) => http.delete(`/admin/users/${path(userId)}`)
export const purgeUser = (userId) => http.delete(`/admin/users/${path(userId)}/purge`)
export const requestPurgeUser = (userId, data) => http.post(`/admin/users/${path(userId)}/purge-requests`, data)
export const getOperationRequests = (params) => http.get('/admin/users/operation-requests', { params })
export const reviewOperationRequest = (id, data) => http.put(`/admin/users/operation-requests/${path(id)}/review`, data)
export const getUserEntitlement = (userId) => http.get(`/admin/users/${path(userId)}/entitlement`)
export const getUserPurchases = (userId, params) => http.get(`/admin/users/${path(userId)}/entitlement/purchases`, { params })
export const getUserUsageLogs = (userId, params) => http.get(`/admin/users/${path(userId)}/entitlement/usage-logs`, { params })
export const adjustUserEntitlement = (userId, data) => http.post(`/admin/users/${path(userId)}/entitlement/adjustments`, data)
export const createRewardOrder = (userId, data) => http.post(`/admin/users/${path(userId)}/entitlement/reward-orders`, data)
export const getAdminRefunds = (params) => http.get('/admin/entitlements/refunds', { params })
export const reviewRefund = (refundNo, data) => http.put(`/admin/entitlements/refunds/${path(refundNo)}/review`, data)
export const completeDemoRefund = (refundNo, data) => http.post(`/admin/entitlements/refunds/${path(refundNo)}/demo-result`, data)
