<script setup>
import { reactive, ref, watch } from 'vue'
import { X } from 'lucide-vue-next'
import { updateUser } from '@/api/operations'
import { getApiErrorMessage } from '@/utils/apiError'
import '@/views/operations/operations.css'
const props = defineProps({ open: Boolean, user: { type: Object, default: null }, allowRole: Boolean })
const emit = defineEmits(['close', 'saved'])
const saving = ref(false), error = ref('')
const form = reactive({ nickname: '', email: '', phone: '', role: 2, maxConnections: '', dailyQuotaMinutes: '', expireTime: '' })
function reset(){Object.assign(form,{nickname:props.user?.nickname||'',email:props.user?.email||'',phone:props.user?.phone||'',role:Number(props.user?.role??2),maxConnections:props.user?.maxConnections??'',dailyQuotaMinutes:props.user?.dailyQuotaMinutes??'',expireTime:props.user?.expireTime?String(props.user.expireTime).slice(0,16):''});error.value=''}
async function submit(){if(!props.user?.userId)return;saving.value=true;error.value='';const payload={nickname:form.nickname.trim()||null,email:form.email.trim()||null,phone:form.phone.trim()||null,maxConnections:form.maxConnections===''?null:Number(form.maxConnections),dailyQuotaMinutes:form.dailyQuotaMinutes===''?null:Number(form.dailyQuotaMinutes),expireTime:form.expireTime?`${form.expireTime}:00`:null};if(props.allowRole)payload.role=Number(form.role);try{const response=await updateUser(props.user.userId,payload);if(response.data?.code!==200)throw new Error(response.data?.message||'用户保存失败');emit('saved',response.data.data)}catch(cause){error.value=cause instanceof Error&&!cause.response?cause.message:getApiErrorMessage(cause,'用户保存失败')}finally{saving.value=false}}
watch([()=>props.open,()=>props.user?.userId],([open])=>{if(open)reset()},{immediate:true})
</script>
<template><Teleport to="body"><div v-if="open" class="operations-modal-backdrop" @click.self="!saving && emit('close')"><form class="operations-modal glass-panel operations-form" @submit.prevent="submit"><header class="operations-modal-header"><div><p class="page-kicker">用户管理</p><h3>{{ user?.username }}</h3></div><button class="icon-button" type="button" :disabled="saving" title="关闭" @click="emit('close')"><X :size="18" /></button></header><p v-if="error" class="alert error">{{ error }}</p><label><span>昵称</span><input v-model="form.nickname" maxlength="64" /></label><div class="operations-form-row"><label><span>邮箱</span><input v-model="form.email" type="email" maxlength="128" /></label><label><span>手机号</span><input v-model="form.phone" maxlength="11" /></label></div><div class="operations-form-row"><label><span>最大连接数</span><input v-model="form.maxConnections" type="number" min="1" /></label><label><span>每日配额分钟</span><input v-model="form.dailyQuotaMinutes" type="number" min="0" /></label></div><div class="operations-form-row"><label><span>过期时间</span><input v-model="form.expireTime" type="datetime-local" /></label><label><span>角色</span><select v-model="form.role" :disabled="!allowRole"><option :value="2">普通用户</option><option :value="1">管理员</option></select></label></div><button type="submit" :disabled="saving">{{ saving?'保存中...':'保存用户' }}</button></form></div></Teleport></template>
